### ISSUE TITLE
fatal error: lv2.h: No such file or directory

### ISSUE THREAD

**Issue by Qualphey** [lsp-plugins/lsp-plugin-fw#2] opened 2022-08-06 13:09 UTC
I'm tryina build `lsp-sampler` with with the latest `devel` configuration but `lsp-plugin-fw` fails:
```
lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/lv2/lv2.h:27:10: fatal error: lv2.h: No such file or directory
   27 | #include <lv2.h>
```
This could as well be a problem with my local configuration, though this started happening after I've rebased my PRs on the latest `devel` and updated other modules.

Running out of ideas. :/

**Comment by sadko4u** [comment] 2022-08-06 13:54
This is duplicate of this issue:
https://github.com/sadko4u/lsp-plugins/issues/268

Seems that backward compatibility for `<lv2.h>` header was broken in latest LV2 release.
I'm going to replace the include directive as @drobilla recommended in the topic above.

**Comment by sadko4u** [comment] 2022-08-06 14:04
This commit fixed the issue:
https://github.com/lsp-plugins/lsp-plugin-fw/commit/9ff9fe56e3ff6829d8a7daff2c555bc5c0a28c7c

**Closed as completed by sadko4u** 2022-08-06 14:04 UTC
